/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// EmailWarmUpRequest Channel: Email Required when `kind` is \"warmup\". The gradual sending schedule for the Auto Warm Up campaign.
type EmailWarmUpRequest struct {
	// Required. The ordered stages that make up the campaign's sending schedule.
	Stages []EmailWarmUpStage `json:"stages"`
	// How the stage schedule should be treated:   * `recommended` - (Default) OneSignal may adjust the provided stages based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * `custom` - The stages provided are sent as-is. 
	Strategy NullableString `json:"strategy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EmailWarmUpRequest EmailWarmUpRequest

// NewEmailWarmUpRequest instantiates a new EmailWarmUpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailWarmUpRequest(stages []EmailWarmUpStage) *EmailWarmUpRequest {
	this := EmailWarmUpRequest{}
	this.Stages = stages
	return &this
}

// NewEmailWarmUpRequestWithDefaults instantiates a new EmailWarmUpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailWarmUpRequestWithDefaults() *EmailWarmUpRequest {
	this := EmailWarmUpRequest{}
	return &this
}

// GetStages returns the Stages field value
func (o *EmailWarmUpRequest) GetStages() []EmailWarmUpStage {
	if o == nil {
		var ret []EmailWarmUpStage
		return ret
	}

	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value
// and a boolean to check if the value has been set.
func (o *EmailWarmUpRequest) GetStagesOk() ([]EmailWarmUpStage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stages, true
}

// SetStages sets field value
func (o *EmailWarmUpRequest) SetStages(v []EmailWarmUpStage) {
	o.Stages = v
}

// GetStrategy returns the Strategy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailWarmUpRequest) GetStrategy() string {
	if o == nil || o.Strategy.Get() == nil {
		var ret string
		return ret
	}
	return *o.Strategy.Get()
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailWarmUpRequest) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Strategy.Get(), o.Strategy.IsSet()
}

// HasStrategy returns a boolean if a field has been set.
func (o *EmailWarmUpRequest) HasStrategy() bool {
	if o != nil && o.Strategy.IsSet() {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given NullableString and assigns it to the Strategy field.
func (o *EmailWarmUpRequest) SetStrategy(v string) {
	o.Strategy.Set(&v)
}
// SetStrategyNil sets the value for Strategy to be an explicit nil
func (o *EmailWarmUpRequest) SetStrategyNil() {
	o.Strategy.Set(nil)
}

// UnsetStrategy ensures that no value is present for Strategy, not even an explicit nil
func (o *EmailWarmUpRequest) UnsetStrategy() {
	o.Strategy.Unset()
}

func (o EmailWarmUpRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["stages"] = o.Stages
	}
	if o.Strategy.IsSet() {
		toSerialize["strategy"] = o.Strategy.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *EmailWarmUpRequest) UnmarshalJSON(bytes []byte) (err error) {
	varEmailWarmUpRequest := _EmailWarmUpRequest{}

	if err = json.Unmarshal(bytes, &varEmailWarmUpRequest); err == nil {
		*o = EmailWarmUpRequest(varEmailWarmUpRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "stages")
		delete(additionalProperties, "strategy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEmailWarmUpRequest struct {
	value *EmailWarmUpRequest
	isSet bool
}

func (v NullableEmailWarmUpRequest) Get() *EmailWarmUpRequest {
	return v.value
}

func (v *NullableEmailWarmUpRequest) Set(val *EmailWarmUpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailWarmUpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailWarmUpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailWarmUpRequest(val *EmailWarmUpRequest) *NullableEmailWarmUpRequest {
	return &NullableEmailWarmUpRequest{value: val, isSet: true}
}

func (v NullableEmailWarmUpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailWarmUpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


