/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.2.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// RateLimitError struct for RateLimitError
type RateLimitError struct {
	Errors []string `json:"errors,omitempty"`
	Limit *string `json:"limit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RateLimitError RateLimitError

// NewRateLimitError instantiates a new RateLimitError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitError() *RateLimitError {
	this := RateLimitError{}
	return &this
}

// NewRateLimitErrorWithDefaults instantiates a new RateLimitError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitErrorWithDefaults() *RateLimitError {
	this := RateLimitError{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *RateLimitError) GetErrors() []string {
	if o == nil || o.Errors == nil {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetErrorsOk() ([]string, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *RateLimitError) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *RateLimitError) SetErrors(v []string) {
	o.Errors = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *RateLimitError) GetLimit() string {
	if o == nil || o.Limit == nil {
		var ret string
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateLimitError) GetLimitOk() (*string, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *RateLimitError) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given string and assigns it to the Limit field.
func (o *RateLimitError) SetLimit(v string) {
	o.Limit = &v
}

func (o RateLimitError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *RateLimitError) UnmarshalJSON(bytes []byte) (err error) {
	varRateLimitError := _RateLimitError{}

	if err = json.Unmarshal(bytes, &varRateLimitError); err == nil {
		*o = RateLimitError(varRateLimitError)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "errors")
		delete(additionalProperties, "limit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRateLimitError struct {
	value *RateLimitError
	isSet bool
}

func (v NullableRateLimitError) Get() *RateLimitError {
	return v.value
}

func (v *NullableRateLimitError) Set(val *RateLimitError) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitError) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitError(val *RateLimitError) *NullableRateLimitError {
	return &NullableRateLimitError{value: val, isSet: true}
}

func (v NullableRateLimitError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


