/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.3.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// ApiKeyToken struct for ApiKeyToken
type ApiKeyToken struct {
	TokenId *string `json:"token_id,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Name *string `json:"name,omitempty"`
	IpAllowlistMode *string `json:"ip_allowlist_mode,omitempty"`
	IpAllowlist []string `json:"ip_allowlist,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiKeyToken ApiKeyToken

// NewApiKeyToken instantiates a new ApiKeyToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyToken() *ApiKeyToken {
	this := ApiKeyToken{}
	return &this
}

// NewApiKeyTokenWithDefaults instantiates a new ApiKeyToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyTokenWithDefaults() *ApiKeyToken {
	this := ApiKeyToken{}
	return &this
}

// GetTokenId returns the TokenId field value if set, zero value otherwise.
func (o *ApiKeyToken) GetTokenId() string {
	if o == nil || o.TokenId == nil {
		var ret string
		return ret
	}
	return *o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetTokenIdOk() (*string, bool) {
	if o == nil || o.TokenId == nil {
		return nil, false
	}
	return o.TokenId, true
}

// HasTokenId returns a boolean if a field has been set.
func (o *ApiKeyToken) HasTokenId() bool {
	if o != nil && o.TokenId != nil {
		return true
	}

	return false
}

// SetTokenId gets a reference to the given string and assigns it to the TokenId field.
func (o *ApiKeyToken) SetTokenId(v string) {
	o.TokenId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ApiKeyToken) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ApiKeyToken) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ApiKeyToken) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ApiKeyToken) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ApiKeyToken) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ApiKeyToken) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiKeyToken) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiKeyToken) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiKeyToken) SetName(v string) {
	o.Name = &v
}

// GetIpAllowlistMode returns the IpAllowlistMode field value if set, zero value otherwise.
func (o *ApiKeyToken) GetIpAllowlistMode() string {
	if o == nil || o.IpAllowlistMode == nil {
		var ret string
		return ret
	}
	return *o.IpAllowlistMode
}

// GetIpAllowlistModeOk returns a tuple with the IpAllowlistMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetIpAllowlistModeOk() (*string, bool) {
	if o == nil || o.IpAllowlistMode == nil {
		return nil, false
	}
	return o.IpAllowlistMode, true
}

// HasIpAllowlistMode returns a boolean if a field has been set.
func (o *ApiKeyToken) HasIpAllowlistMode() bool {
	if o != nil && o.IpAllowlistMode != nil {
		return true
	}

	return false
}

// SetIpAllowlistMode gets a reference to the given string and assigns it to the IpAllowlistMode field.
func (o *ApiKeyToken) SetIpAllowlistMode(v string) {
	o.IpAllowlistMode = &v
}

// GetIpAllowlist returns the IpAllowlist field value if set, zero value otherwise.
func (o *ApiKeyToken) GetIpAllowlist() []string {
	if o == nil || o.IpAllowlist == nil {
		var ret []string
		return ret
	}
	return o.IpAllowlist
}

// GetIpAllowlistOk returns a tuple with the IpAllowlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyToken) GetIpAllowlistOk() ([]string, bool) {
	if o == nil || o.IpAllowlist == nil {
		return nil, false
	}
	return o.IpAllowlist, true
}

// HasIpAllowlist returns a boolean if a field has been set.
func (o *ApiKeyToken) HasIpAllowlist() bool {
	if o != nil && o.IpAllowlist != nil {
		return true
	}

	return false
}

// SetIpAllowlist gets a reference to the given []string and assigns it to the IpAllowlist field.
func (o *ApiKeyToken) SetIpAllowlist(v []string) {
	o.IpAllowlist = v
}

func (o ApiKeyToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TokenId != nil {
		toSerialize["token_id"] = o.TokenId
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.IpAllowlistMode != nil {
		toSerialize["ip_allowlist_mode"] = o.IpAllowlistMode
	}
	if o.IpAllowlist != nil {
		toSerialize["ip_allowlist"] = o.IpAllowlist
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ApiKeyToken) UnmarshalJSON(bytes []byte) (err error) {
	varApiKeyToken := _ApiKeyToken{}

	if err = json.Unmarshal(bytes, &varApiKeyToken); err == nil {
		*o = ApiKeyToken(varApiKeyToken)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "token_id")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "name")
		delete(additionalProperties, "ip_allowlist_mode")
		delete(additionalProperties, "ip_allowlist")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiKeyToken struct {
	value *ApiKeyToken
	isSet bool
}

func (v NullableApiKeyToken) Get() *ApiKeyToken {
	return v.value
}

func (v *NullableApiKeyToken) Set(val *ApiKeyToken) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyToken) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyToken(val *ApiKeyToken) *NullableApiKeyToken {
	return &NullableApiKeyToken{value: val, isSet: true}
}

func (v NullableApiKeyToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


