/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// EstimateNotificationRecipientsRequest The targeting subset of notification fields this endpoint honors. `included_segments` (or its `\"All\"` shorthand) is required. `excluded_segments`, `filters`, `include_aliases`, and `target_channel` narrow that segment-based audience further when present. Use `target_channel` to select which platforms to count. Other notification targeting fields (`include_subscription_ids` and the other raw subscription id/token fields, and the individual `isIos` / `isAndroid` / etc. platform flags) are not read by this endpoint. All non-targeting notification fields (content, delivery options, and so on) are accepted, but ignored. 
type EstimateNotificationRecipientsRequest struct {
	// The segment names you want to target. Users in these segments will receive a notification. This targeting parameter is only compatible with excluded_segments. Example: [\"Active Users\", \"Inactive Users\"] `\"All\"` is a shorthand for every subscribed user: if the array includes the string `\"All\"` and the app has no segment actually named `All`, it targets all subscribers instead of a literal segment lookup. 
	IncludedSegments []string `json:"included_segments,omitempty"`
	// Segment that will be excluded when sending. Users in these segments will not receive a notification, even if they were included in included_segments. This targeting parameter is only compatible with included_segments. Example: [\"Active Users\", \"Inactive Users\"] 
	ExcludedSegments []string `json:"excluded_segments,omitempty"`
	// The OneSignal App ID for your app, which can be found in Keys & IDs.
	AppId string `json:"app_id"`
	Filters []FilterExpression `json:"filters,omitempty"`
	// Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \"external_id\": [\"exId1\", \"extId2\"], \"internal_label\": [\"id1\", \"id2\"] } Keys must match API spellings exactly (for example the label for External ID is the string `external_id`; arbitrary keys such as camelCase variants are not aliases and may yield no recipients). Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.
	IncludeAliases map[string][]string `json:"include_aliases,omitempty"`
	// Which platforms to count recipients for. Selects the same default platforms Create notification would use for the channel. Individual platform flags (`isIos`, `isAndroid`, etc.) are not supported by this endpoint.
	TargetChannel *string `json:"target_channel,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EstimateNotificationRecipientsRequest EstimateNotificationRecipientsRequest

// NewEstimateNotificationRecipientsRequest instantiates a new EstimateNotificationRecipientsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateNotificationRecipientsRequest(appId string) *EstimateNotificationRecipientsRequest {
	this := EstimateNotificationRecipientsRequest{}
	this.AppId = appId
	return &this
}

// NewEstimateNotificationRecipientsRequestWithDefaults instantiates a new EstimateNotificationRecipientsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateNotificationRecipientsRequestWithDefaults() *EstimateNotificationRecipientsRequest {
	this := EstimateNotificationRecipientsRequest{}
	return &this
}

// GetIncludedSegments returns the IncludedSegments field value if set, zero value otherwise.
func (o *EstimateNotificationRecipientsRequest) GetIncludedSegments() []string {
	if o == nil || o.IncludedSegments == nil {
		var ret []string
		return ret
	}
	return o.IncludedSegments
}

// GetIncludedSegmentsOk returns a tuple with the IncludedSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateNotificationRecipientsRequest) GetIncludedSegmentsOk() ([]string, bool) {
	if o == nil || o.IncludedSegments == nil {
		return nil, false
	}
	return o.IncludedSegments, true
}

// HasIncludedSegments returns a boolean if a field has been set.
func (o *EstimateNotificationRecipientsRequest) HasIncludedSegments() bool {
	if o != nil && o.IncludedSegments != nil {
		return true
	}

	return false
}

// SetIncludedSegments gets a reference to the given []string and assigns it to the IncludedSegments field.
func (o *EstimateNotificationRecipientsRequest) SetIncludedSegments(v []string) {
	o.IncludedSegments = v
}

// GetExcludedSegments returns the ExcludedSegments field value if set, zero value otherwise.
func (o *EstimateNotificationRecipientsRequest) GetExcludedSegments() []string {
	if o == nil || o.ExcludedSegments == nil {
		var ret []string
		return ret
	}
	return o.ExcludedSegments
}

// GetExcludedSegmentsOk returns a tuple with the ExcludedSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateNotificationRecipientsRequest) GetExcludedSegmentsOk() ([]string, bool) {
	if o == nil || o.ExcludedSegments == nil {
		return nil, false
	}
	return o.ExcludedSegments, true
}

// HasExcludedSegments returns a boolean if a field has been set.
func (o *EstimateNotificationRecipientsRequest) HasExcludedSegments() bool {
	if o != nil && o.ExcludedSegments != nil {
		return true
	}

	return false
}

// SetExcludedSegments gets a reference to the given []string and assigns it to the ExcludedSegments field.
func (o *EstimateNotificationRecipientsRequest) SetExcludedSegments(v []string) {
	o.ExcludedSegments = v
}

// GetAppId returns the AppId field value
func (o *EstimateNotificationRecipientsRequest) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *EstimateNotificationRecipientsRequest) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *EstimateNotificationRecipientsRequest) SetAppId(v string) {
	o.AppId = v
}

// GetFilters returns the Filters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EstimateNotificationRecipientsRequest) GetFilters() []FilterExpression {
	if o == nil {
		var ret []FilterExpression
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EstimateNotificationRecipientsRequest) GetFiltersOk() ([]FilterExpression, bool) {
	if o == nil || o.Filters == nil {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *EstimateNotificationRecipientsRequest) HasFilters() bool {
	if o != nil && o.Filters != nil {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []FilterExpression and assigns it to the Filters field.
func (o *EstimateNotificationRecipientsRequest) SetFilters(v []FilterExpression) {
	o.Filters = v
}

// GetIncludeAliases returns the IncludeAliases field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EstimateNotificationRecipientsRequest) GetIncludeAliases() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}
	return o.IncludeAliases
}

// GetIncludeAliasesOk returns a tuple with the IncludeAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EstimateNotificationRecipientsRequest) GetIncludeAliasesOk() (*map[string][]string, bool) {
	if o == nil || o.IncludeAliases == nil {
		return nil, false
	}
	return &o.IncludeAliases, true
}

// HasIncludeAliases returns a boolean if a field has been set.
func (o *EstimateNotificationRecipientsRequest) HasIncludeAliases() bool {
	if o != nil && o.IncludeAliases != nil {
		return true
	}

	return false
}

// SetIncludeAliases gets a reference to the given map[string][]string and assigns it to the IncludeAliases field.
func (o *EstimateNotificationRecipientsRequest) SetIncludeAliases(v map[string][]string) {
	o.IncludeAliases = v
}

// GetTargetChannel returns the TargetChannel field value if set, zero value otherwise.
func (o *EstimateNotificationRecipientsRequest) GetTargetChannel() string {
	if o == nil || o.TargetChannel == nil {
		var ret string
		return ret
	}
	return *o.TargetChannel
}

// GetTargetChannelOk returns a tuple with the TargetChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateNotificationRecipientsRequest) GetTargetChannelOk() (*string, bool) {
	if o == nil || o.TargetChannel == nil {
		return nil, false
	}
	return o.TargetChannel, true
}

// HasTargetChannel returns a boolean if a field has been set.
func (o *EstimateNotificationRecipientsRequest) HasTargetChannel() bool {
	if o != nil && o.TargetChannel != nil {
		return true
	}

	return false
}

// SetTargetChannel gets a reference to the given string and assigns it to the TargetChannel field.
func (o *EstimateNotificationRecipientsRequest) SetTargetChannel(v string) {
	o.TargetChannel = &v
}

func (o EstimateNotificationRecipientsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludedSegments != nil {
		toSerialize["included_segments"] = o.IncludedSegments
	}
	if o.ExcludedSegments != nil {
		toSerialize["excluded_segments"] = o.ExcludedSegments
	}
	if true {
		toSerialize["app_id"] = o.AppId
	}
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	if o.IncludeAliases != nil {
		toSerialize["include_aliases"] = o.IncludeAliases
	}
	if o.TargetChannel != nil {
		toSerialize["target_channel"] = o.TargetChannel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *EstimateNotificationRecipientsRequest) UnmarshalJSON(bytes []byte) (err error) {
	varEstimateNotificationRecipientsRequest := _EstimateNotificationRecipientsRequest{}

	if err = json.Unmarshal(bytes, &varEstimateNotificationRecipientsRequest); err == nil {
		*o = EstimateNotificationRecipientsRequest(varEstimateNotificationRecipientsRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "included_segments")
		delete(additionalProperties, "excluded_segments")
		delete(additionalProperties, "app_id")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "include_aliases")
		delete(additionalProperties, "target_channel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEstimateNotificationRecipientsRequest struct {
	value *EstimateNotificationRecipientsRequest
	isSet bool
}

func (v NullableEstimateNotificationRecipientsRequest) Get() *EstimateNotificationRecipientsRequest {
	return v.value
}

func (v *NullableEstimateNotificationRecipientsRequest) Set(val *EstimateNotificationRecipientsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateNotificationRecipientsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateNotificationRecipientsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateNotificationRecipientsRequest(val *EstimateNotificationRecipientsRequest) *NullableEstimateNotificationRecipientsRequest {
	return &NullableEstimateNotificationRecipientsRequest{value: val, isSet: true}
}

func (v NullableEstimateNotificationRecipientsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateNotificationRecipientsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


