/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.1.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// GetSegmentsSuccessResponse struct for GetSegmentsSuccessResponse
type GetSegmentsSuccessResponse struct {
	// The number of Segments in the response.
	TotalCount *int32 `json:"total_count,omitempty"`
	// Set with the offset query parameter. Default 0.
	Offset *int32 `json:"offset,omitempty"`
	// Maximum number of Segments returned. Default 300.
	Limit *int32 `json:"limit,omitempty"`
	// An array containing the Segment information.
	Segments []SegmentData `json:"segments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetSegmentsSuccessResponse GetSegmentsSuccessResponse

// NewGetSegmentsSuccessResponse instantiates a new GetSegmentsSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSegmentsSuccessResponse() *GetSegmentsSuccessResponse {
	this := GetSegmentsSuccessResponse{}
	return &this
}

// NewGetSegmentsSuccessResponseWithDefaults instantiates a new GetSegmentsSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSegmentsSuccessResponseWithDefaults() *GetSegmentsSuccessResponse {
	this := GetSegmentsSuccessResponse{}
	return &this
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *GetSegmentsSuccessResponse) GetTotalCount() int32 {
	if o == nil || o.TotalCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSegmentsSuccessResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || o.TotalCount == nil {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *GetSegmentsSuccessResponse) HasTotalCount() bool {
	if o != nil && o.TotalCount != nil {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *GetSegmentsSuccessResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetSegmentsSuccessResponse) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSegmentsSuccessResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetSegmentsSuccessResponse) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetSegmentsSuccessResponse) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetSegmentsSuccessResponse) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSegmentsSuccessResponse) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetSegmentsSuccessResponse) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetSegmentsSuccessResponse) SetLimit(v int32) {
	o.Limit = &v
}

// GetSegments returns the Segments field value if set, zero value otherwise.
func (o *GetSegmentsSuccessResponse) GetSegments() []SegmentData {
	if o == nil || o.Segments == nil {
		var ret []SegmentData
		return ret
	}
	return o.Segments
}

// GetSegmentsOk returns a tuple with the Segments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSegmentsSuccessResponse) GetSegmentsOk() ([]SegmentData, bool) {
	if o == nil || o.Segments == nil {
		return nil, false
	}
	return o.Segments, true
}

// HasSegments returns a boolean if a field has been set.
func (o *GetSegmentsSuccessResponse) HasSegments() bool {
	if o != nil && o.Segments != nil {
		return true
	}

	return false
}

// SetSegments gets a reference to the given []SegmentData and assigns it to the Segments field.
func (o *GetSegmentsSuccessResponse) SetSegments(v []SegmentData) {
	o.Segments = v
}

func (o GetSegmentsSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TotalCount != nil {
		toSerialize["total_count"] = o.TotalCount
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Segments != nil {
		toSerialize["segments"] = o.Segments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetSegmentsSuccessResponse) UnmarshalJSON(bytes []byte) (err error) {
	varGetSegmentsSuccessResponse := _GetSegmentsSuccessResponse{}

	if err = json.Unmarshal(bytes, &varGetSegmentsSuccessResponse); err == nil {
		*o = GetSegmentsSuccessResponse(varGetSegmentsSuccessResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "total_count")
		delete(additionalProperties, "offset")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "segments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSegmentsSuccessResponse struct {
	value *GetSegmentsSuccessResponse
	isSet bool
}

func (v NullableGetSegmentsSuccessResponse) Get() *GetSegmentsSuccessResponse {
	return v.value
}

func (v *NullableGetSegmentsSuccessResponse) Set(val *GetSegmentsSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSegmentsSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSegmentsSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSegmentsSuccessResponse(val *GetSegmentsSuccessResponse) *NullableGetSegmentsSuccessResponse {
	return &NullableGetSegmentsSuccessResponse{value: val, isSet: true}
}

func (v NullableGetSegmentsSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSegmentsSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


