/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.0.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// UpdatePlayerSuccessResponse struct for UpdatePlayerSuccessResponse
type UpdatePlayerSuccessResponse struct {
	Success *bool `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePlayerSuccessResponse UpdatePlayerSuccessResponse

// NewUpdatePlayerSuccessResponse instantiates a new UpdatePlayerSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlayerSuccessResponse() *UpdatePlayerSuccessResponse {
	this := UpdatePlayerSuccessResponse{}
	return &this
}

// NewUpdatePlayerSuccessResponseWithDefaults instantiates a new UpdatePlayerSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlayerSuccessResponseWithDefaults() *UpdatePlayerSuccessResponse {
	this := UpdatePlayerSuccessResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdatePlayerSuccessResponse) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlayerSuccessResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdatePlayerSuccessResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdatePlayerSuccessResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o UpdatePlayerSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *UpdatePlayerSuccessResponse) UnmarshalJSON(bytes []byte) (err error) {
	varUpdatePlayerSuccessResponse := _UpdatePlayerSuccessResponse{}

	if err = json.Unmarshal(bytes, &varUpdatePlayerSuccessResponse); err == nil {
		*o = UpdatePlayerSuccessResponse(varUpdatePlayerSuccessResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePlayerSuccessResponse struct {
	value *UpdatePlayerSuccessResponse
	isSet bool
}

func (v NullableUpdatePlayerSuccessResponse) Get() *UpdatePlayerSuccessResponse {
	return v.value
}

func (v *NullableUpdatePlayerSuccessResponse) Set(val *UpdatePlayerSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlayerSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlayerSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlayerSuccessResponse(val *UpdatePlayerSuccessResponse) *NullableUpdatePlayerSuccessResponse {
	return &NullableUpdatePlayerSuccessResponse{value: val, isSet: true}
}

func (v NullableUpdatePlayerSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlayerSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


