/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.0.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// UpdateLiveActivitySuccessResponse struct for UpdateLiveActivitySuccessResponse
type UpdateLiveActivitySuccessResponse struct {
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateLiveActivitySuccessResponse UpdateLiveActivitySuccessResponse

// NewUpdateLiveActivitySuccessResponse instantiates a new UpdateLiveActivitySuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLiveActivitySuccessResponse() *UpdateLiveActivitySuccessResponse {
	this := UpdateLiveActivitySuccessResponse{}
	return &this
}

// NewUpdateLiveActivitySuccessResponseWithDefaults instantiates a new UpdateLiveActivitySuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLiveActivitySuccessResponseWithDefaults() *UpdateLiveActivitySuccessResponse {
	this := UpdateLiveActivitySuccessResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateLiveActivitySuccessResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLiveActivitySuccessResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateLiveActivitySuccessResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateLiveActivitySuccessResponse) SetId(v string) {
	o.Id = &v
}

func (o UpdateLiveActivitySuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *UpdateLiveActivitySuccessResponse) UnmarshalJSON(bytes []byte) (err error) {
	varUpdateLiveActivitySuccessResponse := _UpdateLiveActivitySuccessResponse{}

	if err = json.Unmarshal(bytes, &varUpdateLiveActivitySuccessResponse); err == nil {
		*o = UpdateLiveActivitySuccessResponse(varUpdateLiveActivitySuccessResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateLiveActivitySuccessResponse struct {
	value *UpdateLiveActivitySuccessResponse
	isSet bool
}

func (v NullableUpdateLiveActivitySuccessResponse) Get() *UpdateLiveActivitySuccessResponse {
	return v.value
}

func (v *NullableUpdateLiveActivitySuccessResponse) Set(val *UpdateLiveActivitySuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLiveActivitySuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLiveActivitySuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLiveActivitySuccessResponse(val *UpdateLiveActivitySuccessResponse) *NullableUpdateLiveActivitySuccessResponse {
	return &NullableUpdateLiveActivitySuccessResponse{value: val, isSet: true}
}

func (v NullableUpdateLiveActivitySuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLiveActivitySuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


