/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
	"time"
)

// EmailWarmUpStage Channel: Email One stage of an Auto Warm Up campaign's sending schedule.
type EmailWarmUpStage struct {
	// ISO 8601 timestamp for the start of this stage. Sending for this stage will not begin before this time.
	Start time.Time `json:"start"`
	// ISO 8601 timestamp for the end of this stage. This stage's quota is expected to be sent by this time.
	End time.Time `json:"end"`
	// Number of emails to send during this stage.
	Quota int32 `json:"quota"`
	// Whether this stage has been picked up and acknowledged by the warm-up scheduler. Not accepted on create. This is only present when reading back a campaign.
	Acked *bool `json:"acked,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EmailWarmUpStage EmailWarmUpStage

// NewEmailWarmUpStage instantiates a new EmailWarmUpStage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailWarmUpStage(start time.Time, end time.Time, quota int32) *EmailWarmUpStage {
	this := EmailWarmUpStage{}
	this.Start = start
	this.End = end
	this.Quota = quota
	return &this
}

// NewEmailWarmUpStageWithDefaults instantiates a new EmailWarmUpStage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailWarmUpStageWithDefaults() *EmailWarmUpStage {
	this := EmailWarmUpStage{}
	return &this
}

// GetStart returns the Start field value
func (o *EmailWarmUpStage) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *EmailWarmUpStage) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *EmailWarmUpStage) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *EmailWarmUpStage) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *EmailWarmUpStage) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *EmailWarmUpStage) SetEnd(v time.Time) {
	o.End = v
}

// GetQuota returns the Quota field value
func (o *EmailWarmUpStage) GetQuota() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *EmailWarmUpStage) GetQuotaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *EmailWarmUpStage) SetQuota(v int32) {
	o.Quota = v
}

// GetAcked returns the Acked field value if set, zero value otherwise.
func (o *EmailWarmUpStage) GetAcked() bool {
	if o == nil || o.Acked == nil {
		var ret bool
		return ret
	}
	return *o.Acked
}

// GetAckedOk returns a tuple with the Acked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailWarmUpStage) GetAckedOk() (*bool, bool) {
	if o == nil || o.Acked == nil {
		return nil, false
	}
	return o.Acked, true
}

// HasAcked returns a boolean if a field has been set.
func (o *EmailWarmUpStage) HasAcked() bool {
	if o != nil && o.Acked != nil {
		return true
	}

	return false
}

// SetAcked gets a reference to the given bool and assigns it to the Acked field.
func (o *EmailWarmUpStage) SetAcked(v bool) {
	o.Acked = &v
}

func (o EmailWarmUpStage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["start"] = o.Start
	}
	if true {
		toSerialize["end"] = o.End
	}
	if true {
		toSerialize["quota"] = o.Quota
	}
	if o.Acked != nil {
		toSerialize["acked"] = o.Acked
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *EmailWarmUpStage) UnmarshalJSON(bytes []byte) (err error) {
	varEmailWarmUpStage := _EmailWarmUpStage{}

	if err = json.Unmarshal(bytes, &varEmailWarmUpStage); err == nil {
		*o = EmailWarmUpStage(varEmailWarmUpStage)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "start")
		delete(additionalProperties, "end")
		delete(additionalProperties, "quota")
		delete(additionalProperties, "acked")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEmailWarmUpStage struct {
	value *EmailWarmUpStage
	isSet bool
}

func (v NullableEmailWarmUpStage) Get() *EmailWarmUpStage {
	return v.value
}

func (v *NullableEmailWarmUpStage) Set(val *EmailWarmUpStage) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailWarmUpStage) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailWarmUpStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailWarmUpStage(val *EmailWarmUpStage) *NullableEmailWarmUpStage {
	return &NullableEmailWarmUpStage{value: val, isSet: true}
}

func (v NullableEmailWarmUpStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailWarmUpStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


