/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.4.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// UpdateSubscriptionRequestBody struct for UpdateSubscriptionRequestBody
type UpdateSubscriptionRequestBody struct {
	Subscription *SubscriptionObject `json:"subscription,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSubscriptionRequestBody UpdateSubscriptionRequestBody

// NewUpdateSubscriptionRequestBody instantiates a new UpdateSubscriptionRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSubscriptionRequestBody() *UpdateSubscriptionRequestBody {
	this := UpdateSubscriptionRequestBody{}
	return &this
}

// NewUpdateSubscriptionRequestBodyWithDefaults instantiates a new UpdateSubscriptionRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSubscriptionRequestBodyWithDefaults() *UpdateSubscriptionRequestBody {
	this := UpdateSubscriptionRequestBody{}
	return &this
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *UpdateSubscriptionRequestBody) GetSubscription() SubscriptionObject {
	if o == nil || o.Subscription == nil {
		var ret SubscriptionObject
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSubscriptionRequestBody) GetSubscriptionOk() (*SubscriptionObject, bool) {
	if o == nil || o.Subscription == nil {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *UpdateSubscriptionRequestBody) HasSubscription() bool {
	if o != nil && o.Subscription != nil {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionObject and assigns it to the Subscription field.
func (o *UpdateSubscriptionRequestBody) SetSubscription(v SubscriptionObject) {
	o.Subscription = &v
}

func (o UpdateSubscriptionRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Subscription != nil {
		toSerialize["subscription"] = o.Subscription
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *UpdateSubscriptionRequestBody) UnmarshalJSON(bytes []byte) (err error) {
	varUpdateSubscriptionRequestBody := _UpdateSubscriptionRequestBody{}

	if err = json.Unmarshal(bytes, &varUpdateSubscriptionRequestBody); err == nil {
		*o = UpdateSubscriptionRequestBody(varUpdateSubscriptionRequestBody)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "subscription")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSubscriptionRequestBody struct {
	value *UpdateSubscriptionRequestBody
	isSet bool
}

func (v NullableUpdateSubscriptionRequestBody) Get() *UpdateSubscriptionRequestBody {
	return v.value
}

func (v *NullableUpdateSubscriptionRequestBody) Set(val *UpdateSubscriptionRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSubscriptionRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSubscriptionRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSubscriptionRequestBody(val *UpdateSubscriptionRequestBody) *NullableUpdateSubscriptionRequestBody {
	return &NullableUpdateSubscriptionRequestBody{value: val, isSet: true}
}

func (v NullableUpdateSubscriptionRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSubscriptionRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


