/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// JourneyEarlyExitRulesOnSegment struct for JourneyEarlyExitRulesOnSegment
type JourneyEarlyExitRulesOnSegment struct {
	// Exit when the user enters any of these segments.
	IncludedSegmentIds []string `json:"included_segment_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JourneyEarlyExitRulesOnSegment JourneyEarlyExitRulesOnSegment

// NewJourneyEarlyExitRulesOnSegment instantiates a new JourneyEarlyExitRulesOnSegment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJourneyEarlyExitRulesOnSegment() *JourneyEarlyExitRulesOnSegment {
	this := JourneyEarlyExitRulesOnSegment{}
	return &this
}

// NewJourneyEarlyExitRulesOnSegmentWithDefaults instantiates a new JourneyEarlyExitRulesOnSegment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJourneyEarlyExitRulesOnSegmentWithDefaults() *JourneyEarlyExitRulesOnSegment {
	this := JourneyEarlyExitRulesOnSegment{}
	return &this
}

// GetIncludedSegmentIds returns the IncludedSegmentIds field value if set, zero value otherwise.
func (o *JourneyEarlyExitRulesOnSegment) GetIncludedSegmentIds() []string {
	if o == nil || o.IncludedSegmentIds == nil {
		var ret []string
		return ret
	}
	return o.IncludedSegmentIds
}

// GetIncludedSegmentIdsOk returns a tuple with the IncludedSegmentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JourneyEarlyExitRulesOnSegment) GetIncludedSegmentIdsOk() ([]string, bool) {
	if o == nil || o.IncludedSegmentIds == nil {
		return nil, false
	}
	return o.IncludedSegmentIds, true
}

// HasIncludedSegmentIds returns a boolean if a field has been set.
func (o *JourneyEarlyExitRulesOnSegment) HasIncludedSegmentIds() bool {
	if o != nil && o.IncludedSegmentIds != nil {
		return true
	}

	return false
}

// SetIncludedSegmentIds gets a reference to the given []string and assigns it to the IncludedSegmentIds field.
func (o *JourneyEarlyExitRulesOnSegment) SetIncludedSegmentIds(v []string) {
	o.IncludedSegmentIds = v
}

func (o JourneyEarlyExitRulesOnSegment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludedSegmentIds != nil {
		toSerialize["included_segment_ids"] = o.IncludedSegmentIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *JourneyEarlyExitRulesOnSegment) UnmarshalJSON(bytes []byte) (err error) {
	varJourneyEarlyExitRulesOnSegment := _JourneyEarlyExitRulesOnSegment{}

	if err = json.Unmarshal(bytes, &varJourneyEarlyExitRulesOnSegment); err == nil {
		*o = JourneyEarlyExitRulesOnSegment(varJourneyEarlyExitRulesOnSegment)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "included_segment_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJourneyEarlyExitRulesOnSegment struct {
	value *JourneyEarlyExitRulesOnSegment
	isSet bool
}

func (v NullableJourneyEarlyExitRulesOnSegment) Get() *JourneyEarlyExitRulesOnSegment {
	return v.value
}

func (v *NullableJourneyEarlyExitRulesOnSegment) Set(val *JourneyEarlyExitRulesOnSegment) {
	v.value = val
	v.isSet = true
}

func (v NullableJourneyEarlyExitRulesOnSegment) IsSet() bool {
	return v.isSet
}

func (v *NullableJourneyEarlyExitRulesOnSegment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJourneyEarlyExitRulesOnSegment(val *JourneyEarlyExitRulesOnSegment) *NullableJourneyEarlyExitRulesOnSegment {
	return &NullableJourneyEarlyExitRulesOnSegment{value: val, isSet: true}
}

func (v NullableJourneyEarlyExitRulesOnSegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJourneyEarlyExitRulesOnSegment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


