/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// CreateJourneyRequest Writable fields for Create journey. Journeys are always created in the draft state. Server-controlled fields such as state or id are rejected.
type CreateJourneyRequest struct {
	// Journey name, up to 300 characters.
	Name string `json:"name"`
	// Optional journey description, up to 1024 characters.
	Description NullableString `json:"description,omitempty"`
	Audience *JourneyAudience `json:"audience,omitempty"`
	EarlyExit NullableJourneyEarlyExit `json:"early_exit,omitempty"`
	ReentryRules NullableJourneyReentryRules `json:"reentry_rules,omitempty"`
	Schedule NullableJourneySchedule `json:"schedule,omitempty"`
	// Ordered list of journey nodes. Server-assigned id fields are rejected on create.
	Nodes []JourneyNode `json:"nodes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateJourneyRequest CreateJourneyRequest

// NewCreateJourneyRequest instantiates a new CreateJourneyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJourneyRequest(name string) *CreateJourneyRequest {
	this := CreateJourneyRequest{}
	this.Name = name
	return &this
}

// NewCreateJourneyRequestWithDefaults instantiates a new CreateJourneyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJourneyRequestWithDefaults() *CreateJourneyRequest {
	this := CreateJourneyRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateJourneyRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateJourneyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateJourneyRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJourneyRequest) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJourneyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateJourneyRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateJourneyRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateJourneyRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetAudience returns the Audience field value if set, zero value otherwise.
func (o *CreateJourneyRequest) GetAudience() JourneyAudience {
	if o == nil || o.Audience == nil {
		var ret JourneyAudience
		return ret
	}
	return *o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJourneyRequest) GetAudienceOk() (*JourneyAudience, bool) {
	if o == nil || o.Audience == nil {
		return nil, false
	}
	return o.Audience, true
}

// HasAudience returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasAudience() bool {
	if o != nil && o.Audience != nil {
		return true
	}

	return false
}

// SetAudience gets a reference to the given JourneyAudience and assigns it to the Audience field.
func (o *CreateJourneyRequest) SetAudience(v JourneyAudience) {
	o.Audience = &v
}

// GetEarlyExit returns the EarlyExit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJourneyRequest) GetEarlyExit() JourneyEarlyExit {
	if o == nil || o.EarlyExit.Get() == nil {
		var ret JourneyEarlyExit
		return ret
	}
	return *o.EarlyExit.Get()
}

// GetEarlyExitOk returns a tuple with the EarlyExit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJourneyRequest) GetEarlyExitOk() (*JourneyEarlyExit, bool) {
	if o == nil {
		return nil, false
	}
	return o.EarlyExit.Get(), o.EarlyExit.IsSet()
}

// HasEarlyExit returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasEarlyExit() bool {
	if o != nil && o.EarlyExit.IsSet() {
		return true
	}

	return false
}

// SetEarlyExit gets a reference to the given NullableJourneyEarlyExit and assigns it to the EarlyExit field.
func (o *CreateJourneyRequest) SetEarlyExit(v JourneyEarlyExit) {
	o.EarlyExit.Set(&v)
}
// SetEarlyExitNil sets the value for EarlyExit to be an explicit nil
func (o *CreateJourneyRequest) SetEarlyExitNil() {
	o.EarlyExit.Set(nil)
}

// UnsetEarlyExit ensures that no value is present for EarlyExit, not even an explicit nil
func (o *CreateJourneyRequest) UnsetEarlyExit() {
	o.EarlyExit.Unset()
}

// GetReentryRules returns the ReentryRules field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJourneyRequest) GetReentryRules() JourneyReentryRules {
	if o == nil || o.ReentryRules.Get() == nil {
		var ret JourneyReentryRules
		return ret
	}
	return *o.ReentryRules.Get()
}

// GetReentryRulesOk returns a tuple with the ReentryRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJourneyRequest) GetReentryRulesOk() (*JourneyReentryRules, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReentryRules.Get(), o.ReentryRules.IsSet()
}

// HasReentryRules returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasReentryRules() bool {
	if o != nil && o.ReentryRules.IsSet() {
		return true
	}

	return false
}

// SetReentryRules gets a reference to the given NullableJourneyReentryRules and assigns it to the ReentryRules field.
func (o *CreateJourneyRequest) SetReentryRules(v JourneyReentryRules) {
	o.ReentryRules.Set(&v)
}
// SetReentryRulesNil sets the value for ReentryRules to be an explicit nil
func (o *CreateJourneyRequest) SetReentryRulesNil() {
	o.ReentryRules.Set(nil)
}

// UnsetReentryRules ensures that no value is present for ReentryRules, not even an explicit nil
func (o *CreateJourneyRequest) UnsetReentryRules() {
	o.ReentryRules.Unset()
}

// GetSchedule returns the Schedule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJourneyRequest) GetSchedule() JourneySchedule {
	if o == nil || o.Schedule.Get() == nil {
		var ret JourneySchedule
		return ret
	}
	return *o.Schedule.Get()
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJourneyRequest) GetScheduleOk() (*JourneySchedule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schedule.Get(), o.Schedule.IsSet()
}

// HasSchedule returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasSchedule() bool {
	if o != nil && o.Schedule.IsSet() {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given NullableJourneySchedule and assigns it to the Schedule field.
func (o *CreateJourneyRequest) SetSchedule(v JourneySchedule) {
	o.Schedule.Set(&v)
}
// SetScheduleNil sets the value for Schedule to be an explicit nil
func (o *CreateJourneyRequest) SetScheduleNil() {
	o.Schedule.Set(nil)
}

// UnsetSchedule ensures that no value is present for Schedule, not even an explicit nil
func (o *CreateJourneyRequest) UnsetSchedule() {
	o.Schedule.Unset()
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *CreateJourneyRequest) GetNodes() []JourneyNode {
	if o == nil || o.Nodes == nil {
		var ret []JourneyNode
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJourneyRequest) GetNodesOk() ([]JourneyNode, bool) {
	if o == nil || o.Nodes == nil {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *CreateJourneyRequest) HasNodes() bool {
	if o != nil && o.Nodes != nil {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []JourneyNode and assigns it to the Nodes field.
func (o *CreateJourneyRequest) SetNodes(v []JourneyNode) {
	o.Nodes = v
}

func (o CreateJourneyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Audience != nil {
		toSerialize["audience"] = o.Audience
	}
	if o.EarlyExit.IsSet() {
		toSerialize["early_exit"] = o.EarlyExit.Get()
	}
	if o.ReentryRules.IsSet() {
		toSerialize["reentry_rules"] = o.ReentryRules.Get()
	}
	if o.Schedule.IsSet() {
		toSerialize["schedule"] = o.Schedule.Get()
	}
	if o.Nodes != nil {
		toSerialize["nodes"] = o.Nodes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateJourneyRequest) UnmarshalJSON(bytes []byte) (err error) {
	varCreateJourneyRequest := _CreateJourneyRequest{}

	if err = json.Unmarshal(bytes, &varCreateJourneyRequest); err == nil {
		*o = CreateJourneyRequest(varCreateJourneyRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "audience")
		delete(additionalProperties, "early_exit")
		delete(additionalProperties, "reentry_rules")
		delete(additionalProperties, "schedule")
		delete(additionalProperties, "nodes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateJourneyRequest struct {
	value *CreateJourneyRequest
	isSet bool
}

func (v NullableCreateJourneyRequest) Get() *CreateJourneyRequest {
	return v.value
}

func (v *NullableCreateJourneyRequest) Set(val *CreateJourneyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJourneyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJourneyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJourneyRequest(val *CreateJourneyRequest) *NullableCreateJourneyRequest {
	return &NullableCreateJourneyRequest{value: val, isSet: true}
}

func (v NullableCreateJourneyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJourneyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


