/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.0.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// DeleteSegmentBadRequestResponse struct for DeleteSegmentBadRequestResponse
type DeleteSegmentBadRequestResponse struct {
	Erorrs []string `json:"erorrs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeleteSegmentBadRequestResponse DeleteSegmentBadRequestResponse

// NewDeleteSegmentBadRequestResponse instantiates a new DeleteSegmentBadRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSegmentBadRequestResponse() *DeleteSegmentBadRequestResponse {
	this := DeleteSegmentBadRequestResponse{}
	return &this
}

// NewDeleteSegmentBadRequestResponseWithDefaults instantiates a new DeleteSegmentBadRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSegmentBadRequestResponseWithDefaults() *DeleteSegmentBadRequestResponse {
	this := DeleteSegmentBadRequestResponse{}
	return &this
}

// GetErorrs returns the Erorrs field value if set, zero value otherwise.
func (o *DeleteSegmentBadRequestResponse) GetErorrs() []string {
	if o == nil || o.Erorrs == nil {
		var ret []string
		return ret
	}
	return o.Erorrs
}

// GetErorrsOk returns a tuple with the Erorrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSegmentBadRequestResponse) GetErorrsOk() ([]string, bool) {
	if o == nil || o.Erorrs == nil {
		return nil, false
	}
	return o.Erorrs, true
}

// HasErorrs returns a boolean if a field has been set.
func (o *DeleteSegmentBadRequestResponse) HasErorrs() bool {
	if o != nil && o.Erorrs != nil {
		return true
	}

	return false
}

// SetErorrs gets a reference to the given []string and assigns it to the Erorrs field.
func (o *DeleteSegmentBadRequestResponse) SetErorrs(v []string) {
	o.Erorrs = v
}

func (o DeleteSegmentBadRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Erorrs != nil {
		toSerialize["erorrs"] = o.Erorrs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DeleteSegmentBadRequestResponse) UnmarshalJSON(bytes []byte) (err error) {
	varDeleteSegmentBadRequestResponse := _DeleteSegmentBadRequestResponse{}

	if err = json.Unmarshal(bytes, &varDeleteSegmentBadRequestResponse); err == nil {
		*o = DeleteSegmentBadRequestResponse(varDeleteSegmentBadRequestResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "erorrs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteSegmentBadRequestResponse struct {
	value *DeleteSegmentBadRequestResponse
	isSet bool
}

func (v NullableDeleteSegmentBadRequestResponse) Get() *DeleteSegmentBadRequestResponse {
	return v.value
}

func (v *NullableDeleteSegmentBadRequestResponse) Set(val *DeleteSegmentBadRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSegmentBadRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSegmentBadRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSegmentBadRequestResponse(val *DeleteSegmentBadRequestResponse) *NullableDeleteSegmentBadRequestResponse {
	return &NullableDeleteSegmentBadRequestResponse{value: val, isSet: true}
}

func (v NullableDeleteSegmentBadRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSegmentBadRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


