/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.3.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// ExportSubscriptionsRequestBody struct for ExportSubscriptionsRequestBody
type ExportSubscriptionsRequestBody struct {
	// Additional fields that you wish to include. Currently supports location, country, rooted, notification_types, ip, external_user_id, web_auth, and web_p256.
	ExtraFields []string `json:"extra_fields,omitempty"`
	// Export all devices with a last_active timestamp greater than this time.  Unixtime in seconds.
	LastActiveSince *string `json:"last_active_since,omitempty"`
	// Export all devices belonging to the segment.
	SegmentName *string `json:"segment_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExportSubscriptionsRequestBody ExportSubscriptionsRequestBody

// NewExportSubscriptionsRequestBody instantiates a new ExportSubscriptionsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportSubscriptionsRequestBody() *ExportSubscriptionsRequestBody {
	this := ExportSubscriptionsRequestBody{}
	return &this
}

// NewExportSubscriptionsRequestBodyWithDefaults instantiates a new ExportSubscriptionsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportSubscriptionsRequestBodyWithDefaults() *ExportSubscriptionsRequestBody {
	this := ExportSubscriptionsRequestBody{}
	return &this
}

// GetExtraFields returns the ExtraFields field value if set, zero value otherwise.
func (o *ExportSubscriptionsRequestBody) GetExtraFields() []string {
	if o == nil || o.ExtraFields == nil {
		var ret []string
		return ret
	}
	return o.ExtraFields
}

// GetExtraFieldsOk returns a tuple with the ExtraFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportSubscriptionsRequestBody) GetExtraFieldsOk() ([]string, bool) {
	if o == nil || o.ExtraFields == nil {
		return nil, false
	}
	return o.ExtraFields, true
}

// HasExtraFields returns a boolean if a field has been set.
func (o *ExportSubscriptionsRequestBody) HasExtraFields() bool {
	if o != nil && o.ExtraFields != nil {
		return true
	}

	return false
}

// SetExtraFields gets a reference to the given []string and assigns it to the ExtraFields field.
func (o *ExportSubscriptionsRequestBody) SetExtraFields(v []string) {
	o.ExtraFields = v
}

// GetLastActiveSince returns the LastActiveSince field value if set, zero value otherwise.
func (o *ExportSubscriptionsRequestBody) GetLastActiveSince() string {
	if o == nil || o.LastActiveSince == nil {
		var ret string
		return ret
	}
	return *o.LastActiveSince
}

// GetLastActiveSinceOk returns a tuple with the LastActiveSince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportSubscriptionsRequestBody) GetLastActiveSinceOk() (*string, bool) {
	if o == nil || o.LastActiveSince == nil {
		return nil, false
	}
	return o.LastActiveSince, true
}

// HasLastActiveSince returns a boolean if a field has been set.
func (o *ExportSubscriptionsRequestBody) HasLastActiveSince() bool {
	if o != nil && o.LastActiveSince != nil {
		return true
	}

	return false
}

// SetLastActiveSince gets a reference to the given string and assigns it to the LastActiveSince field.
func (o *ExportSubscriptionsRequestBody) SetLastActiveSince(v string) {
	o.LastActiveSince = &v
}

// GetSegmentName returns the SegmentName field value if set, zero value otherwise.
func (o *ExportSubscriptionsRequestBody) GetSegmentName() string {
	if o == nil || o.SegmentName == nil {
		var ret string
		return ret
	}
	return *o.SegmentName
}

// GetSegmentNameOk returns a tuple with the SegmentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportSubscriptionsRequestBody) GetSegmentNameOk() (*string, bool) {
	if o == nil || o.SegmentName == nil {
		return nil, false
	}
	return o.SegmentName, true
}

// HasSegmentName returns a boolean if a field has been set.
func (o *ExportSubscriptionsRequestBody) HasSegmentName() bool {
	if o != nil && o.SegmentName != nil {
		return true
	}

	return false
}

// SetSegmentName gets a reference to the given string and assigns it to the SegmentName field.
func (o *ExportSubscriptionsRequestBody) SetSegmentName(v string) {
	o.SegmentName = &v
}

func (o ExportSubscriptionsRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExtraFields != nil {
		toSerialize["extra_fields"] = o.ExtraFields
	}
	if o.LastActiveSince != nil {
		toSerialize["last_active_since"] = o.LastActiveSince
	}
	if o.SegmentName != nil {
		toSerialize["segment_name"] = o.SegmentName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ExportSubscriptionsRequestBody) UnmarshalJSON(bytes []byte) (err error) {
	varExportSubscriptionsRequestBody := _ExportSubscriptionsRequestBody{}

	if err = json.Unmarshal(bytes, &varExportSubscriptionsRequestBody); err == nil {
		*o = ExportSubscriptionsRequestBody(varExportSubscriptionsRequestBody)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "extra_fields")
		delete(additionalProperties, "last_active_since")
		delete(additionalProperties, "segment_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExportSubscriptionsRequestBody struct {
	value *ExportSubscriptionsRequestBody
	isSet bool
}

func (v NullableExportSubscriptionsRequestBody) Get() *ExportSubscriptionsRequestBody {
	return v.value
}

func (v *NullableExportSubscriptionsRequestBody) Set(val *ExportSubscriptionsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableExportSubscriptionsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableExportSubscriptionsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportSubscriptionsRequestBody(val *ExportSubscriptionsRequestBody) *NullableExportSubscriptionsRequestBody {
	return &NullableExportSubscriptionsRequestBody{value: val, isSet: true}
}

func (v NullableExportSubscriptionsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportSubscriptionsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


