/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.13.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// JourneyListAudience Entry audience reduced to its kind. Use View journey for the full audience configuration.
type JourneyListAudience struct {
	// Audience kind.
	Kind *string `json:"kind,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JourneyListAudience JourneyListAudience

// NewJourneyListAudience instantiates a new JourneyListAudience object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJourneyListAudience() *JourneyListAudience {
	this := JourneyListAudience{}
	return &this
}

// NewJourneyListAudienceWithDefaults instantiates a new JourneyListAudience object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJourneyListAudienceWithDefaults() *JourneyListAudience {
	this := JourneyListAudience{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *JourneyListAudience) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JourneyListAudience) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *JourneyListAudience) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *JourneyListAudience) SetKind(v string) {
	o.Kind = &v
}

func (o JourneyListAudience) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *JourneyListAudience) UnmarshalJSON(bytes []byte) (err error) {
	varJourneyListAudience := _JourneyListAudience{}

	if err = json.Unmarshal(bytes, &varJourneyListAudience); err == nil {
		*o = JourneyListAudience(varJourneyListAudience)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "kind")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJourneyListAudience struct {
	value *JourneyListAudience
	isSet bool
}

func (v NullableJourneyListAudience) Get() *JourneyListAudience {
	return v.value
}

func (v *NullableJourneyListAudience) Set(val *JourneyListAudience) {
	v.value = val
	v.isSet = true
}

func (v NullableJourneyListAudience) IsSet() bool {
	return v.isSet
}

func (v *NullableJourneyListAudience) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJourneyListAudience(val *JourneyListAudience) *NullableJourneyListAudience {
	return &NullableJourneyListAudience{value: val, isSet: true}
}

func (v NullableJourneyListAudience) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJourneyListAudience) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


