/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.0.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// UpdatePlayerTagsSuccessResponse struct for UpdatePlayerTagsSuccessResponse
type UpdatePlayerTagsSuccessResponse struct {
	Success *bool `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePlayerTagsSuccessResponse UpdatePlayerTagsSuccessResponse

// NewUpdatePlayerTagsSuccessResponse instantiates a new UpdatePlayerTagsSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlayerTagsSuccessResponse() *UpdatePlayerTagsSuccessResponse {
	this := UpdatePlayerTagsSuccessResponse{}
	return &this
}

// NewUpdatePlayerTagsSuccessResponseWithDefaults instantiates a new UpdatePlayerTagsSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlayerTagsSuccessResponseWithDefaults() *UpdatePlayerTagsSuccessResponse {
	this := UpdatePlayerTagsSuccessResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdatePlayerTagsSuccessResponse) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlayerTagsSuccessResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdatePlayerTagsSuccessResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdatePlayerTagsSuccessResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o UpdatePlayerTagsSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *UpdatePlayerTagsSuccessResponse) UnmarshalJSON(bytes []byte) (err error) {
	varUpdatePlayerTagsSuccessResponse := _UpdatePlayerTagsSuccessResponse{}

	if err = json.Unmarshal(bytes, &varUpdatePlayerTagsSuccessResponse); err == nil {
		*o = UpdatePlayerTagsSuccessResponse(varUpdatePlayerTagsSuccessResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePlayerTagsSuccessResponse struct {
	value *UpdatePlayerTagsSuccessResponse
	isSet bool
}

func (v NullableUpdatePlayerTagsSuccessResponse) Get() *UpdatePlayerTagsSuccessResponse {
	return v.value
}

func (v *NullableUpdatePlayerTagsSuccessResponse) Set(val *UpdatePlayerTagsSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlayerTagsSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlayerTagsSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlayerTagsSuccessResponse(val *UpdatePlayerTagsSuccessResponse) *NullableUpdatePlayerTagsSuccessResponse {
	return &NullableUpdatePlayerTagsSuccessResponse{value: val, isSet: true}
}

func (v NullableUpdatePlayerTagsSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlayerTagsSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


