/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// JourneyReentryRules Controls whether and how soon a user can re-enter the journey. null means re-entry is not allowed.
type JourneyReentryRules struct {
	// Minimum seconds before a user can re-enter. Must be at least 600 (10 minutes).
	DurationSeconds NullableInt32 `json:"duration_seconds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JourneyReentryRules JourneyReentryRules

// NewJourneyReentryRules instantiates a new JourneyReentryRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJourneyReentryRules() *JourneyReentryRules {
	this := JourneyReentryRules{}
	return &this
}

// NewJourneyReentryRulesWithDefaults instantiates a new JourneyReentryRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJourneyReentryRulesWithDefaults() *JourneyReentryRules {
	this := JourneyReentryRules{}
	return &this
}

// GetDurationSeconds returns the DurationSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JourneyReentryRules) GetDurationSeconds() int32 {
	if o == nil || o.DurationSeconds.Get() == nil {
		var ret int32
		return ret
	}
	return *o.DurationSeconds.Get()
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JourneyReentryRules) GetDurationSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationSeconds.Get(), o.DurationSeconds.IsSet()
}

// HasDurationSeconds returns a boolean if a field has been set.
func (o *JourneyReentryRules) HasDurationSeconds() bool {
	if o != nil && o.DurationSeconds.IsSet() {
		return true
	}

	return false
}

// SetDurationSeconds gets a reference to the given NullableInt32 and assigns it to the DurationSeconds field.
func (o *JourneyReentryRules) SetDurationSeconds(v int32) {
	o.DurationSeconds.Set(&v)
}
// SetDurationSecondsNil sets the value for DurationSeconds to be an explicit nil
func (o *JourneyReentryRules) SetDurationSecondsNil() {
	o.DurationSeconds.Set(nil)
}

// UnsetDurationSeconds ensures that no value is present for DurationSeconds, not even an explicit nil
func (o *JourneyReentryRules) UnsetDurationSeconds() {
	o.DurationSeconds.Unset()
}

func (o JourneyReentryRules) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DurationSeconds.IsSet() {
		toSerialize["duration_seconds"] = o.DurationSeconds.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *JourneyReentryRules) UnmarshalJSON(bytes []byte) (err error) {
	varJourneyReentryRules := _JourneyReentryRules{}

	if err = json.Unmarshal(bytes, &varJourneyReentryRules); err == nil {
		*o = JourneyReentryRules(varJourneyReentryRules)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "duration_seconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJourneyReentryRules struct {
	value *JourneyReentryRules
	isSet bool
}

func (v NullableJourneyReentryRules) Get() *JourneyReentryRules {
	return v.value
}

func (v *NullableJourneyReentryRules) Set(val *JourneyReentryRules) {
	v.value = val
	v.isSet = true
}

func (v NullableJourneyReentryRules) IsSet() bool {
	return v.isSet
}

func (v *NullableJourneyReentryRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJourneyReentryRules(val *JourneyReentryRules) *NullableJourneyReentryRules {
	return &NullableJourneyReentryRules{value: val, isSet: true}
}

func (v NullableJourneyReentryRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJourneyReentryRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


