/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.4.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// CreateUserConflictResponseErrorsInner struct for CreateUserConflictResponseErrorsInner
type CreateUserConflictResponseErrorsInner struct {
	Code *string `json:"code,omitempty"`
	Title *string `json:"title,omitempty"`
	Meta *CreateUserConflictResponseErrorsItemsMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateUserConflictResponseErrorsInner CreateUserConflictResponseErrorsInner

// NewCreateUserConflictResponseErrorsInner instantiates a new CreateUserConflictResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserConflictResponseErrorsInner() *CreateUserConflictResponseErrorsInner {
	this := CreateUserConflictResponseErrorsInner{}
	return &this
}

// NewCreateUserConflictResponseErrorsInnerWithDefaults instantiates a new CreateUserConflictResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserConflictResponseErrorsInnerWithDefaults() *CreateUserConflictResponseErrorsInner {
	this := CreateUserConflictResponseErrorsInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateUserConflictResponseErrorsInner) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserConflictResponseErrorsInner) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateUserConflictResponseErrorsInner) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CreateUserConflictResponseErrorsInner) SetCode(v string) {
	o.Code = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateUserConflictResponseErrorsInner) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserConflictResponseErrorsInner) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateUserConflictResponseErrorsInner) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateUserConflictResponseErrorsInner) SetTitle(v string) {
	o.Title = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *CreateUserConflictResponseErrorsInner) GetMeta() CreateUserConflictResponseErrorsItemsMeta {
	if o == nil || o.Meta == nil {
		var ret CreateUserConflictResponseErrorsItemsMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserConflictResponseErrorsInner) GetMetaOk() (*CreateUserConflictResponseErrorsItemsMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *CreateUserConflictResponseErrorsInner) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given CreateUserConflictResponseErrorsItemsMeta and assigns it to the Meta field.
func (o *CreateUserConflictResponseErrorsInner) SetMeta(v CreateUserConflictResponseErrorsItemsMeta) {
	o.Meta = &v
}

func (o CreateUserConflictResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateUserConflictResponseErrorsInner) UnmarshalJSON(bytes []byte) (err error) {
	varCreateUserConflictResponseErrorsInner := _CreateUserConflictResponseErrorsInner{}

	if err = json.Unmarshal(bytes, &varCreateUserConflictResponseErrorsInner); err == nil {
		*o = CreateUserConflictResponseErrorsInner(varCreateUserConflictResponseErrorsInner)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "title")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUserConflictResponseErrorsInner struct {
	value *CreateUserConflictResponseErrorsInner
	isSet bool
}

func (v NullableCreateUserConflictResponseErrorsInner) Get() *CreateUserConflictResponseErrorsInner {
	return v.value
}

func (v *NullableCreateUserConflictResponseErrorsInner) Set(val *CreateUserConflictResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserConflictResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserConflictResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserConflictResponseErrorsInner(val *CreateUserConflictResponseErrorsInner) *NullableCreateUserConflictResponseErrorsInner {
	return &NullableCreateUserConflictResponseErrorsInner{value: val, isSet: true}
}

func (v NullableCreateUserConflictResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserConflictResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


