/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 1.0.1
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// DeletePlayerNotFoundResponse struct for DeletePlayerNotFoundResponse
type DeletePlayerNotFoundResponse struct {
	Success *bool `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeletePlayerNotFoundResponse DeletePlayerNotFoundResponse

// NewDeletePlayerNotFoundResponse instantiates a new DeletePlayerNotFoundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePlayerNotFoundResponse() *DeletePlayerNotFoundResponse {
	this := DeletePlayerNotFoundResponse{}
	return &this
}

// NewDeletePlayerNotFoundResponseWithDefaults instantiates a new DeletePlayerNotFoundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePlayerNotFoundResponseWithDefaults() *DeletePlayerNotFoundResponse {
	this := DeletePlayerNotFoundResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *DeletePlayerNotFoundResponse) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePlayerNotFoundResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *DeletePlayerNotFoundResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *DeletePlayerNotFoundResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o DeletePlayerNotFoundResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DeletePlayerNotFoundResponse) UnmarshalJSON(bytes []byte) (err error) {
	varDeletePlayerNotFoundResponse := _DeletePlayerNotFoundResponse{}

	if err = json.Unmarshal(bytes, &varDeletePlayerNotFoundResponse); err == nil {
		*o = DeletePlayerNotFoundResponse(varDeletePlayerNotFoundResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeletePlayerNotFoundResponse struct {
	value *DeletePlayerNotFoundResponse
	isSet bool
}

func (v NullableDeletePlayerNotFoundResponse) Get() *DeletePlayerNotFoundResponse {
	return v.value
}

func (v *NullableDeletePlayerNotFoundResponse) Set(val *DeletePlayerNotFoundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePlayerNotFoundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePlayerNotFoundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePlayerNotFoundResponse(val *DeletePlayerNotFoundResponse) *NullableDeletePlayerNotFoundResponse {
	return &NullableDeletePlayerNotFoundResponse{value: val, isSet: true}
}

func (v NullableDeletePlayerNotFoundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePlayerNotFoundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


