/*
OneSignal

A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com

API version: 5.13.0
Contact: devrel@onesignal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onesignal

import (
	"encoding/json"
)

// JourneyListResponse struct for JourneyListResponse
type JourneyListResponse struct {
	// Journeys ordered by creation time, newest first.
	Journeys []JourneyListItem `json:"journeys,omitempty"`
	// true if more journeys exist beyond this page.
	HasMore *bool `json:"has_more,omitempty"`
	// Cursor for the next page. Present only when has_more is true.
	NextCursor *string `json:"next_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JourneyListResponse JourneyListResponse

// NewJourneyListResponse instantiates a new JourneyListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJourneyListResponse() *JourneyListResponse {
	this := JourneyListResponse{}
	return &this
}

// NewJourneyListResponseWithDefaults instantiates a new JourneyListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJourneyListResponseWithDefaults() *JourneyListResponse {
	this := JourneyListResponse{}
	return &this
}

// GetJourneys returns the Journeys field value if set, zero value otherwise.
func (o *JourneyListResponse) GetJourneys() []JourneyListItem {
	if o == nil || o.Journeys == nil {
		var ret []JourneyListItem
		return ret
	}
	return o.Journeys
}

// GetJourneysOk returns a tuple with the Journeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JourneyListResponse) GetJourneysOk() ([]JourneyListItem, bool) {
	if o == nil || o.Journeys == nil {
		return nil, false
	}
	return o.Journeys, true
}

// HasJourneys returns a boolean if a field has been set.
func (o *JourneyListResponse) HasJourneys() bool {
	if o != nil && o.Journeys != nil {
		return true
	}

	return false
}

// SetJourneys gets a reference to the given []JourneyListItem and assigns it to the Journeys field.
func (o *JourneyListResponse) SetJourneys(v []JourneyListItem) {
	o.Journeys = v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *JourneyListResponse) GetHasMore() bool {
	if o == nil || o.HasMore == nil {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JourneyListResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil || o.HasMore == nil {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *JourneyListResponse) HasHasMore() bool {
	if o != nil && o.HasMore != nil {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *JourneyListResponse) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *JourneyListResponse) GetNextCursor() string {
	if o == nil || o.NextCursor == nil {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JourneyListResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || o.NextCursor == nil {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *JourneyListResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor != nil {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *JourneyListResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o JourneyListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Journeys != nil {
		toSerialize["journeys"] = o.Journeys
	}
	if o.HasMore != nil {
		toSerialize["has_more"] = o.HasMore
	}
	if o.NextCursor != nil {
		toSerialize["next_cursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *JourneyListResponse) UnmarshalJSON(bytes []byte) (err error) {
	varJourneyListResponse := _JourneyListResponse{}

	if err = json.Unmarshal(bytes, &varJourneyListResponse); err == nil {
		*o = JourneyListResponse(varJourneyListResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "journeys")
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "next_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJourneyListResponse struct {
	value *JourneyListResponse
	isSet bool
}

func (v NullableJourneyListResponse) Get() *JourneyListResponse {
	return v.value
}

func (v *NullableJourneyListResponse) Set(val *JourneyListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJourneyListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJourneyListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJourneyListResponse(val *JourneyListResponse) *NullableJourneyListResponse {
	return &NullableJourneyListResponse{value: val, isSet: true}
}

func (v NullableJourneyListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJourneyListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


